package main

import (
	"fmt"
	"testing"
)

func TestStep1SampleInput(t *testing.T) {
	var tests = []struct {
		input    string
		expected int
	}{
		{`..........
...#......
..........
....a.....
..........
.....a....
..........
......#...
..........
..........`, 2},
		{`..........
...#......
#.........
....a.....
........a.
.....a....
..#.......
......#...
..........
..........`, 4},
		{`..........
...#......
#.........
....a.....
........a.
.....a....
..#.......
......A...
..........
..........`, 4},
		{`............
........0...
.....0......
.......0....
....0.......
......A.....
............
............
........A...
.........A..
............
............`, 14},
		{`.bb.`, 2},
		{`.b...b.`, 0},
		{`.
b
b
.`, 2},
		{`.....
..bb.
..bb.
.....`, 12},
	}

	for i, tt := range tests {
		testname := fmt.Sprintf("%d", i)
		t.Run(testname, func(t *testing.T) {
			ans := runStep1(tt.input)
			if ans != tt.expected {
				t.Errorf(`TestStep1SampleInput got %d, expected %d`, ans, tt.expected)
			}
		})
	}
}

func TestStep2SampleInput(t *testing.T) {
	var tests = []struct {
		input    string
		expected int
	}{
		{`T....#....
...T......
.T....#...
.........#
..#.......
..........
...#......
..........
....#.....
..........`, 9},
		{`##....#....#
.#.#....0...
..#.#0....#.
..##...0....
....0....#..
.#...#A....#
...#..#.....
#....#.#....
..#.....A...
....#....A..
.#........#.
...#......##`, 34},
	}

	for i, tt := range tests {
		testname := fmt.Sprintf("%d", i)
		t.Run(testname, func(t *testing.T) {
			ans := runStep2(tt.input)
			if ans != tt.expected {
				t.Errorf(`TestStep2SampleInput got %d, expected %d`, ans, tt.expected)
			}
		})
	}
}
